In [39]:
def dotproduct(array1: list, array2: list): # JULIUS
    """
    This method returns the dot product of two vectors, matrices or a vector and a matrix.
    Input:
        array1: the first array or vector
        array2: the second array or vector
    Returns:
        dot_product
    """

    # Check für Character einfügen -> Check integer
    
    # Vector operations
    if isinstance(array1[0], int) and isinstance(array2[0], int):
        try: 
            assert len(array1) == len(array2), "Vectors must have the same shape!"
            value_beg = 0
            # Get elementwise values from both arrays
            array1 = [int(x) for x in array1]
            array2 = [int(x) for x in array2]
            # Perform bitwise multiplication and add it to final value
            for element in range(len(array1)):
                value_beg += array1[element] * array2[element]
            
            return value_beg  
        
        except AssertionError as msg:
            print(msg)
        
    # Matrix / vector operation, first input a vector
    elif (isinstance(array1[0], int) and isinstance(array2[0], list)):
        try:
            assert len(array1) == len(array2), "Array and vector must be compatible"
            array_dot = [] # initialize return vector
            for column_2 in range(len(array2[0])):
                value_beg = 0 # initialitze element for each position of return vector
                for column_1 in range(len(array1)):
                    # Perform bitwise multiplication of the 
                    value = array1[column_1]*array2[column_1][column_2]
                    value_beg += value
                array_dot.append(value_beg)
            return array_dot
            
        except AssertionError as msg:
            print(msg)
    
    # Matrix / vector operation, second input a vector
    elif (isinstance(array1[0], list) and isinstance(array2[0], int)):
        try:
            assert len(array1) == len(array2), "Array and vector must be compatible"
            array_dot = [] # initialize return vector
            for column_2 in range(len(array1[0])):
                value_beg = 0 # initialitze element for each position of return vector
                for column_1 in range(len(array2)):
                    # Perform bitwise multiplication of the 
                    value = array2[column_1]*array1[column_1][column_2]
                    value_beg += value
                array_dot.append(value_beg)
            return array_dot
            
        except AssertionError as msg:
            print(msg)
        
    # Matrix / Matrix operation        
    elif isinstance(array1[0], list) and isinstance(array2[0], list):
        try:
            assert snp.shape(array1) == snp.shape(array2), "Matrices must have the same shape!"
            array_dot = [] # Initialize return vector
            for row_1 in range(len(array1)):
                array_dot_sub = []
                for column_2 in range(len(array2[0])):
                    value_beg = 0
                    for column_1 in range(len(array1[0])):
                        # Iterate through the rows/cols for array1 and cols/rows for array2
                        value = array1[row_1][column_1]*array2[column_1][column_2]
                        value_beg += value
                    array_dot_sub.append(value_beg)
                array_dot.append(array_dot_sub)
        
            return array_dot

        except AssertionError as msg:
            print(msg)        

In [40]:
# Exc. 9
print("Exc. 9: ")
c1 =[3,6,5]
d1 = [7,2,5]
print(dotproduct(c1,d1))
c2 =[3,5]
d2 = [[7,5,4], [2,1,3]]
print(dotproduct(d2,c2))
print(dotproduct(c2,d2))
c3 = [[7,5], [2,1]]
d3 = [[7,5], [2,1]]
print(dotproduct(c3,d3))

Exc. 9: 
58
[31, 20, 27]
[31, 20, 27]
[[59, 40], [16, 11]]


In [41]:
def append(array1, array2, axis = None):
    """
    This function appends the second input to the first, given they are compatible
    Input:
        array1: first input, can be a Matrix or a Vector
        array2: second input, can be a Matrix or a Vector
        axis: This defines the axis, on which the second input will be appended to the first
    Returns:
        output: input2 appended to input1 at the specified axis
    """
    try:
        assert isinstance(array1, list) and isinstance(array2, list), "Inputs must be vector or arrays" 
        if axis == 0:                           
            if isinstance(array1[0], list) and isinstance(array2[0], list):
                try:
                    assert snp.shape(array1)[1] == snp.shape(array2)[1], "Matrices must have the same dimensionality"
                    array_append = []
                    for vector in array1:
                        array_append.append(vector)
                    for vector in array2:
                        array_append.append(vector)
                    return array_append
                    
                except AssertionError as msg:
                    print(msg)

            # Both are Vectors
            elif isinstance(array1[0], int) and isinstance(array2[0], int):
                for element in array2:
                    array1.append(element)
                     
                return array1

        elif axis == 1:
            
            # Both are Matrices:
            if isinstance(array1[0], list) and isinstance(array2[0], list):
                try: 
                    assert len(array1) == len(array2), "Both input matrices have to be of the same length"
                    for i in range(len(array1)):
                        for x in array2[i]:
                            array1[i].append(x)
                    return array1
                        
                except AssertionError as msg:
                    print(msg)
                    
                # Both are Vectors
            elif isinstance(array1[0], int) and isinstance(array2[0], int):
                for i in array2:
                    array1.append(i)
                return array1
                            
            else:
                raise ValueError("Inputs can't be vector and matrix")
                    

        else:
            # No axis is given
            # Both are Matrices:
            if isinstance(array1[0], list) and isinstance(array2[0], list):
                l = []
                for i in range(len(array1)):
                    for x in array1[i]:
                        l.append(x)
                for i in range(len(array2)):
                    for x in array2[i]:
                        l.append(x)     
                return l  
                        
            # Both are Vectors
            elif isinstance(array1[0], int) and isinstance(array2[0], int):
                for i in array2:
                    array1.append(i)
                return array1
                        
            else:
                raise ValueError("Inputs can't be vector and matrix")
            
    except AssertionError as msg:
                print(msg)        

In [42]:
# Test exc. 5
# Axis = 0
print("Exc. 5: ")
print("Vector and Vector: ", append([1,2,3],[4], axis = 0))
print("Matrix single and Matrix single: ", append([[1,2,3]],[[4,5,6]], axis = 0))
print("Matrix and Matrix: ", append([[1,2],[3,4]], [[5,6], [7,8], [9,10]], axis = 0))
print("Matrix: ", append([[1,2,3], [4,5,6], [7,8,9]], [[10,11,12]], axis=0))
# Axis = 1
print("Vector and Vector: ", append([1,2,3],[4], axis = 1))
print("Matrix single and Matrix single: ", append([[1]],[[4]], axis = 1))
print("Matrix and Matrix: ",append([[1,2],[3,4]], [[5,6], [7,8]], axis = 1))
# Axis = None
print("Vector & Vector without axis: ", append([1,2],[3,4]))
print("Matrix & Matrix without axis: ", append([[1,2],[3,4]], [[5,6], [7,8], [9,10]]))

Exc. 5: 
Vector and Vector:  [1, 2, 3, 4]
Matrix single and Matrix single:  [[1, 2, 3], [4, 5, 6]]
Matrix and Matrix:  [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
Matrix:  [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
Vector and Vector:  [1, 2, 3, 4]
Matrix single and Matrix single:  [[1, 4]]
Matrix and Matrix:  [[1, 2, 5, 6], [3, 4, 7, 8]]
Vector & Vector without axis:  [1, 2, 3, 4]
Matrix & Matrix without axis:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [43]:
def linalg(array1, array2): # get solution of linear equation
        '''
        Designed after functionality of numpy.linalg.solve:
        
        Input:
        array1: Coefficient matrix, must be a square and full-rank matrix
        array2: Ordinate or “dependent variable” values
        
        LinAlgError:
        If array1 is singular or not square
        '''
        try:
            #assert (snp.shape(array1)[0] == snp.shape(array1)[1]), "LinAlgError: Dimension of first input must be equal for rows and columns equal"
            assert (snp.shape(array2)[0] == 1), "Dimension of second input must be one dimensional"
            assert (snp.shape(array1)[1] == snp.shape(array2)[1]), "Dimension of second input must fit to first array"
                
            matrix = []
            for i in range(len(array1)): # get augmented matrix, combine both input (horizontal)
                matrix.append(array1[i])
                matrix[i].append(array2[i])

            matrix_shape = snp.shape(matrix) # get shape of the matrix 

            matrix.sort(reverse=True) # switch rows so that biggest values are on the top

            # to reduced echelon form
            for i in range(min(matrix_shape)): # goal: iterating through each diagonal of the matrix
                if matrix[i][i]!=0: # check if diagonal value is zero
                    diagonal = matrix[i][i]
                    for j in range(matrix_shape[1]): # when not zero, divide the diagonal by itself and all other values in the row
                        matrix[i][j] /= diagonal
                    for k in range(matrix_shape[0]): # operation so that the column will be a pivot column
                        if (matrix[k][i]!=0) and (k!=i): # skip the pivotized row
                            factor = matrix[k][i] 
                            for l in range(matrix_shape[1]):
                                matrix[k][l] -= factor * matrix[i][l] # substract with the above row so that pivot column value is 0

            # case when there are infinite solutions
            for i in range(matrix_shape[0]):
                if matrix[i][-1]!=0:
                    if matrix[i].count(0)==(matrix_shape[1]-1): # count if there are only zero values in a row
                        return "matrix has infinite solution"

            # case when there is no solution
            for i in range(matrix_shape[0]):
                if matrix[i][-1]==0:
                    if matrix[i].count(0)==(matrix_shape[1]-1): # if number of zeros equals the number of unknowns, then no solution
                        return "matrix has no solution"

            # case when there is only one solution
            array = []
            for i in range(matrix_shape[0]):
                array.append(matrix[i][-1])
            return "array(" + str(array) + ")"
        
        except AssertionError as msg:
            print(msg) 

In [44]:
x = [[1,0,-2],[-2,1,6],[3,-2,-5]]
y = [[-1,7,-3]]
linalg_julius(x, y)

[3.0, 1.0, 2.0]

In [45]:
def linalg_julius(array1, array2):

    try:
        assert isinstance(array1[0], list), "Input 1 must be an array"
        assert isinstance(array2[0], list), "Input 2 must be an array"
        assert snp.shape(array1)[0] == snp.shape(array2)[1], "Input 1 and 2 must be compatible"

        # build the combined matrix
        array3 = []
        for index, vector in enumerate(array1):
            vector.append(array2[0][index])
            array3.append(vector)

        n = snp.shape(array3)[1] # Get the number of cols
        n2 = snp.shape(array3)[0] # Get the number of rows
        index = list(range(n2)) # get the indexes   

        for pivot in range(n2): # Iterate over the rows
            pscale = 1.0 / array3[pivot][pivot] # get the necessary scaler to bring the pivot element to 1

            for j in range(n): # adjust all elements in the pivot row with the scaler
                array3[pivot][j] *= pscale
                    
            for i in index[0:pivot] + index[pivot+1:]: #iterate over the rest of the matrix, except for the pivot row
                rscale = array3[i][pivot] # get the scaler for each row element to bring it to zero
                for j in range(n):
                    array3[i][j] = array3[i][j] - rscale * array3[pivot][j] # adjust the row elements

        result = []
        for vector in array3:
            result.append(vector[-1])
        
        return result

    except AssertionError as msg:
        print(msg)

In [46]:
def append(array1, array2, axis = None):
    """
    This function appends the second input to the first, given they are compatible
    Input:
        array1: first input, can be a Matrix or a Vector
        array2: second input, can be a Matrix or a Vector
        axis: This defines the axis, on which the second input will be appended to the first
    Returns:
          output: input2 appended to input1 at the specified axis
    """
    try:
        assert isinstance(array1, list) and isinstance(array2, list), "Inputs must be arrays" 
        # If the second input is to be appended "behind" the first one:
        if axis == 0:                           
            # in case both are Matrices
            if isinstance(array1[0], list) and isinstance(array2[0], list):
                try:
                    assert snp.shape(array1)[1] == snp.shape(array2)[1], "Matrices must have the same dimensionality"
                    array_append = [] # initialize return array
                    for vector in array1: # append all contents of first input to this new array
                        array_append.append(vector)
                    for vector in array2: # append all contents of the second input to this new array
                        array_append.append(vector)
                    return array_append
                    
                except AssertionError as msg:
                    print(msg)
            # Both are Vectors
            elif (isinstance(array1[0], int) and isinstance(array2[0], int)) or (isinstance(array1[0], str) and isinstance(array2[0], str)):
                for element in array2: # append all elements of input 2 to the end of input 1
                    array1.append(element)
                      
                return array1

        elif axis == 1:
              
            # Both are Matrices:
            if isinstance(array1[0], list) and isinstance(array2[0], list):
                try: 
                    assert snp.shape(array1) == snp.shape(array2), "Both input matrices must have the same dimensionality"
                    for i in range(len(array1)):
                        for x in array2[i]:
                            array1[i].append(x)
                    return array1
                        
                except AssertionError as msg:
                    print(msg)
                      
            # Both are Vectors
            elif (isinstance(array1[0], int) and isinstance(array2[0], int)) or (isinstance(array1[0], str) and isinstance(array2[0], str)):
                for i in array2:
                    array1.append(i)
                return array1
                              
            else:
                print(ValueError("Inputs can't be vector and matrix"))
                     

        else:
            # No axis is given
            # Both are Matrices:
            if isinstance(array1[0], list) and isinstance(array2[0], list):
                return_array = [] # initialize return array
                for i in range(len(array1)): # add all elements from the first array
                    for x in array1[i]:
                        if isinstance(x, list):
                            for element in x:
                                return_array.append(element)
                        else:
                            return_array.append(x)
                for i in range(len(array2)): # add all elements from the second array
                    for x in array2[i]:
                        if isinstance(x, list):
                            for element in x:
                                return_array.append(element)
                        else:
                            return_array.append(x)   
                return return_array
                        
            # Both are Vectors
            elif (isinstance(array1[0], int) and isinstance(array2[0], int)) or (isinstance(array1[0], str) and isinstance(array2[0], str)):
                for i in array2: # add all elements of the second input to the first
                    array1.append(i)
                return array1
                          
            # Matrix and vector
            elif (isinstance(array1[0], list) and isinstance(array2[0], int)) or (isinstance(array1[0], list) and isinstance(array2[0], str)):
                output = []
                for vector in array1:
                    for i in vector:
                        output.append(i)
                for element in array2:
                    output.append(element)
                
                return output
    except AssertionError as msg:
                  print(msg)      

In [47]:
import numpy as np
# Warum geht das nicht? Numpy geht
print(append(["a","d"], ["b","c"]))
print(append([["a","b","c"], ["a","b","c"]], ["a","c"]))
print(append([[[1],[2]], [[3],[4]]],[1]))

# Warum geht das? Numpy geht nicht
#print(append([[[1],[2]], [[3],[4]]],[[1],[2]], axis = 1))
#print(np.append([[[1],[2]], [[3],[4]]],[[1],[2]], axis = 1))

# Sieht bei numpy anders aus:
print(append([[[1],[2]], [[3],[4]]],[[1],[2]]))
print(np.append([[[1],[2]], [[3],[4]]],[[1],[2]]))

['a', 'd', 'b', 'c']
['a', 'b', 'c', 'a', 'b', 'c', 'a', 'c']
[[1], [2], [3], [4], 1]
[1, 2, 3, 4, 1, 2]
[1 2 3 4 1 2]


In [48]:
class snp():
    def shape(array: list):
      """
      This method takes an array and returns a tuple with the matrix/vector’s dimension (# rows, # columns)
      Arguments:
          array: list that dimensions need to be discovered
      Returns:
          (row, column[0]): tuple with the shape of the array
      """
      # Check that the input is a list
      if not isinstance(array, list):
          raise TypeError("Array must be a list!")

      # Check if the array is a 1D or 2D array
      try:
          array[0][0]  # Check if the array is a 2D array
          is_2d = True
      except:
          is_2d = False

      # Check that the array is a 2D array with equal length for all elements (if it is a 2D array)
      if is_2d:
          if any(len(array[0]) != len(i) for i in array):
              raise ValueError("Error: Elements in the list have not the same length")

      # Return the dimensions of the array
      if is_2d:
          return (len(array), len(array[0]))
      elif len(array) > 1:
          return (1, len(array))
      else:
          return () # empty tuple, if array was empty

    def check_integer_or_float(array: list):
      """
      This method checks if there are elements in the array which are not integers
      Arguments:
          array: list (1d), or list of list (2d)

      Returns:
          True:  If all elements in the list or list of list are integers
          False: If there is at least one element which is not an integer
      """
      # Check that the input is a list
      if not isinstance(array, list):
         raise TypeError("Input must be a list!")

    # Check whether the elements in the array are integers
      if all(isinstance(x, list) for x in array):
        # The input is a 2D array
          return all(isinstance(i,(int, float)) for row in array for i in row)
      else:
        # The input is a 1D array
          return all(isinstance(i, (int, float)) for i in array)

In [49]:
def dotproduct(array1: list, array2: list):
      """
      This method returns the dot product of two vectors, matrices or a vector and a matrix.
      Input:
          array1: the first array or vector
          array2: the second array or vector
      Returns:
          dot_product
      """
      try:
        assert snp.check_integer_or_float(array1) and snp.check_integer_or_float(array2), "Inputs must be numberical"
        # Vector operations
        if isinstance(array1[0], int) and isinstance(array2[0], int):
            try: 
                assert len(array1) == len(array2), "Vectors must have the same shape!"
                value_beg = 0
                # Get elementwise values from both arrays
                array1 = [int(x) for x in array1]
                array2 = [int(x) for x in array2]
                # Perform bitwise multiplication and add it to final value
                for element in range(len(array1)):
                      value_beg += array1[element] * array2[element]
              
                return value_beg  
          
            except AssertionError as msg:
                print(msg)
        
        # Matrix / vector operation, first input a vector
        elif (isinstance(array1[0], int) and isinstance(array2[0], list)):
            try:
                assert len(array1) == len(array2), "Array and vector must be compatible"
                array_dot = [] # initialize return vector
                for column_2 in range(len(array2[0])):
                    value_beg = 0 # initialitze element for each position of return vector
                    for column_1 in range(len(array1)):
                        # Perform bitwise multiplication of the 
                        value = array1[column_1]*array2[column_1][column_2]
                        value_beg += value
                    array_dot.append(value_beg)
                return array_dot
                
            except AssertionError as msg:
                print(msg)
        
        # Matrix / vector operation, second input a vector
        elif (isinstance(array1[0], list) and isinstance(array2[0], int)):
            try:
                assert len(array1) == len(array2), "Array and vector must be compatible"
                array_dot = [] # initialize return vector
                for column_2 in range(len(array1[0])):
                    value_beg = 0 # initialitze element for each position of return vector
                    for column_1 in range(len(array2)):
                        # Perform bitwise multiplication of the 
                        value = array2[column_1]*array1[column_1][column_2]
                        value_beg += value
                    array_dot.append(value_beg)
                return array_dot
                
            except AssertionError as msg:
                print(msg)
            
        # Matrix / Matrix operation        
        elif isinstance(array1[0], list) and isinstance(array2[0], list):
            try:
                print(snp.shape(array1), snp.shape(array2))
                assert snp.shape(array1)[1] == snp.shape(array2)[0], "Matrices must have compatible shapes (#cols array 1 = #rows array2)!"
                array_dot = [] # Initialize return vector
                for row_1 in range(len(array1)):
                    array_dot_sub = []
                    for column_2 in range(len(array2[1])):
                        value_beg = 0
                        for column_1 in range(len(array1[0])):
                            # Iterate through the rows/cols for array1 and cols/rows for array2
                            #print(column_1, column_2, row_1)
                            value = array1[row_1][column_1]*array2[column_1][column_2]
                            value_beg += value
                        array_dot_sub.append(value_beg)
                    array_dot.append(array_dot_sub)
            
                return array_dot

            except AssertionError as msg:
                print(msg) 

      except AssertionError as msg:
        print(msg)    

In [50]:
c3 = [[7,5], [2,1]]
d4 = [[7,5,2], [2,1,3]]

print(np.dot(c3, d4), "\n")
print(dotproduct(c3, d4))

[[59 40 29]
 [16 11  7]] 

(2, 2) (2, 3)
[[59, 40, 29], [16, 11, 7]]


In [51]:
a = [[1,2,3], [7,8,9]]
b = [[7,8], [9,10]]
print(dotproduct(a,b))
print(np.dot(a,b))

(2, 3) (2, 2)
Matrices must have compatible shapes (#cols array 1 = #rows array2)!
None


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
c = [[[1,2],[3,4]],[[1,7],[8,9]]]
d = [[[1,2],[3,4]],[[1,7],[8,9]]]
print(np.dot(c,d))
print(dotproduct(c,d))

[[[[  7  10]
   [ 17  25]]

  [[ 15  22]
   [ 35  57]]]


 [[[ 22  30]
   [ 57  70]]

  [[ 35  52]
   [ 80 137]]]]
Inputs must be numberical
None


In [ ]:
def linalg(array1, array2):
    """
    This function solves a system of linear equasions utilizing the Gauss algorithm and row reduction.
    Inputs:
        array1: the coefficient matrix
        array2: the ordinate matrix
    Returns:
        array3: the solved matrix with the dependent 
  
    """
      
    try:
        assert isinstance(array1[0], list), "Input 1 must be an array"
        assert isinstance(array2[0], list), "Input 2 must be an array"
        assert snp.shape(array1)[0] == snp.shape(array2)[1], "Input 1 and 2 must be compatible"

        # build the combined matrix
        array3 = []
        for index, vector in enumerate(array1):
            vector.append(array2[0][index])
            array3.append(vector)

        n = snp.shape(array3)[1] # Get the number of cols
        n2 = snp.shape(array3)[0] # Get the number of rows
        index = list(range(n2)) # get the indexes   

        for pivot in range(n2): # Iterate over the rows
            pscale = 1.0 / array3[pivot][pivot] # get the necessary scaler to bring the pivot element to 1

            for j in range(n): # adjust all elements in the pivot row with the scaler
                array3[pivot][j] *= pscale
                    
            for i in index[0:pivot] + index[pivot+1:]: #iterate over the rest of the matrix, except for the pivot row
                rscale = array3[i][pivot] # get the scaler for each row element to bring it to zero
                for j in range(n):
                    array3[i][j] = array3[i][j] - rscale * array3[pivot][j] # adjust the row elements
        result = []
        for vector in array3:
            result.append(vector[-1])
          
        return result
          
    except AssertionError as msg:
        print(msg)